### ISSUE TITLE
MVP -- Create/Edit Chapter Form

### ISSUE THREAD

**Issue by sirenabailie** [sirenabailie/Fan-Fusion-FE#15]
# User Story
As a user, I want to create or edit a chapter with a title and content body, so that I can easily manage the chapters in my book.

# Acceptance Criteria
- [ ] User can input a chapter title.
- [ ] User can input or edit chapter content in a text body.
- [ ] Prevent submission of empty fields.
- [ ]  Upon submission, the user is redirected to the story details page
- [ ]  The form shows appropriate placeholder text 
- [ ] Submit button named 'Publish'

# Dependencies
Backend API

# Dev Notes
* Use Bootstrap Form

![Screenshot 2024-10-15 175305](https://github.com/user-attachments/assets/abdce8e8-b0f0-4b5e-bff1-13aa09aef34a)

**Comment by yarelismartin** [comment]
When you create you will need to pass these properties: Title, Content, UserId, SaveAsDraft, StoryId

**Comment by yarelismartin** [comment]
When you edit you will only need to pass the following properties: Id, Title, Content, SaveAsDraft. You will use the same api call for both create and update because I've made it in the backend where it handles creating and updating since we will later introduce the save as draft button onto this form.
